format="""
 $conda\
 $directory\
 $git_branch\
 $character\
 """

 right_format = """
 $git_status\
 $cmd_duration\
 """
 add_newline = false

 [conda]
 format = ' [ $environment](#dbcd0b) '

 # Prompt symbols 
 # [character]
 # success_symbol = "[](#8EC07C bold)"
 # error_symbol = "[](#AD685A)"
 # vicmd_symbol = "[](#DD8F6E)"

 [directory]
 # format = "($style)[ ](fg:#66CED6)[$path](fg:#66CED6 bold)[ ]($style)"
 # style = "bg:none fg:#312C2E"
 truncation_length = 1
 truncate_to_repo=false

 [git_branch]
 format = "($style)[[ ](fg:#DD8F6E bold)$branch](fg:#DD8F6E bold)[ ]($style)"
 style = "bg:none fg:#312C2E"

 [git_status]
 # $all status$ahead_behind
 format = "[]($style)[$all_status$ahead_behind](bg:#312C2E fg:#b4befe)[ ]($style)"
 style = "bg:none fg:#312C2E"
 conflicted = "="
 ahead =	"⇡${count}"
 behind = "⇣${count}"
 diverged = "⇕⇡${ahead_count}⇣${behind_count}"
 up_to_date = ""
 untracked = "?${count}"
 stashed = ""
 modified = "!${count}"
 staged = "+${count}"
 renamed = "»${count}"
 deleted = "${count}"

 [cmd_duration]
 min_time = 1
 # duration & style 
 format = "[]($style)[[神](bg:#312C2E fg:#eba0ac bold)$duration](bg:#312C2E fg:#BBC3DF)[ ]($style)"
 disabled = false
 style = "bg:none fg:#312C2E"
