# Setups
format="""
$conda\
$directory\
$git_branch\
$character\
"""

right_format = """
$git_status\
$cmd_duration\
"""
add_newline = false 

[conda]
format = ' [ $environment](#FDD36A) '

# Prompt symbols 
[character]
success_symbol = "[](#e0af68 bold)"
error_symbol = "[](#AD685A)"
vicmd_symbol = "[](#DD8F6E)"

[directory]
format = "[]($style)[ ](bg:#393646 fg:#e0af68)[$path](bg:#312C2E fg:#F4EEE0 bold)[ ]($style)"
style = "bg:none fg:#393646"
truncation_length = 1
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#393646 fg:#e0af68 bold)$branch](bg:#393646 fg:#e0af68 )[ ]($style)"
style = "bg:none fg:#393646"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#312C2E fg:#F4EEE0)[ ]($style)"
style = "bg:none fg:#393646"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[神](bg:#393646 fg:#F4EEE0 bold)$duration](bg:#393646 fg:#F4EEE0)[ ]($style)"
disabled = false
style = "bg:none fg:#393646"
