# Setups
format="""
$conda\
$directory\
$git_branch\
$character\
"""

right_format = """
$git_status\
$cmd_duration\
"""
add_newline = false 

[conda]
format = ' [ $environment](#F2F79E) '

[character]
success_symbol = "[](bold)"
error_symbol = "[](bold)"
vicmd_symbol = "[](bold)"

[directory]
# format = "($style)[ ](bg:#393646 fg:#f1d8a5)[$path](bg:#393646 fg:#F7F5EB bold)]($style)"
# style = "bg:none fg:#393646"
truncation_length = 1
truncate_to_repo=false
#
[git_branch]
format = "($style)[[ ](fg:#F3A712 bold)(bold)$branch ](fg:#F3A712)($style)"
# format = "[]($style)[[ ](bg:#393646 fg:#C3B299 bold)$branch](bg:#393646 fg:#C3B299)[ ]($style)"
# style = "bg:none fg:#393646"

[git_status]
format = "[]($style)[$all_status$ahead_behind](bg:#312C2E fg:#F7F5EB)[ ]($style)"
style = "bg:none fg:#393646"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
format = "[]($style)[[神](bg:#393646 fg:#F7F5EB bold)$duration](bg:#393646 fg:#F7F5EB)[ ]($style)"
disabled = false
style = "bg:none fg:#393646"
